import 'package:coffee_app/models/data_models.dart' show Farm, Farmer;

List<Farmer> generateSampleFarmers() {
  return [
    Farmer(
      id: '1',
      firstName: 'John',
      lastName: 'Smith',
      registrationNumber: 'FR001',
      gender: 'Male',
      dateOfBirth: DateTime(1980, 5, 15),
      village: 'Green Valley',
      farms: [
        Farm(
          id: 'F1',
          enumeratorName: 'John Doe',
          kebeleName: 'Kebele A',
          woredaName: 'Woreda 1',
          cooperativeName: 'Coop One',
          farmerName: 'John Smith',
          collectingCenterName: 'Center Alpha',
          plotNumber: 'P1',
          latitude: -1.2800,
          longitude: 36.8500,
          gpsAccuracy: 5.0,
          plotSize: 2.0,
          coffeeAge: 5,
          coffeeType: 'Home Garden',
          disturbance: 1,
          geolocationFlagged: false,
          isApproved: true,
          images: ['https://images.unsplash.com/photo-1592856908193-b9934576cf3d'],
          additionalInfo: 'High yield expected this season.',
        ),
      ],
    ),
    Farmer(
      id: '2',
      firstName: 'Maria',
      lastName: 'Garcia',
      registrationNumber: 'FR002',
      gender: 'Female',
      dateOfBirth: DateTime(1975, 8, 22),
      village: 'Sunny Hills',
      farms: [
        Farm(
          id: 'F2',
          enumeratorName: 'Jane Doe',
          kebeleName: 'Kebele B',
          woredaName: 'Woreda 2',
          cooperativeName: 'Coop Beta',
          farmerName: 'Maria Garcia',
          collectingCenterName: 'Center Beta',
          plotNumber: 'P2',
          latitude: -1.2800,
          longitude: 36.8500,
          gpsAccuracy: 9.5,
          plotSize: 3.5,
          coffeeAge: 7,
          coffeeType: 'Plantation',
          disturbance: 0,
          geolocationFlagged: false,
          isApproved: true,
          images: ['https://images.unsplash.com/photo-1560493676-04071c5f467b'],
          additionalInfo: 'Certified organic.',
        ),
      ],
    ),
    Farmer(
      id: '3',
      firstName: 'David',
      lastName: 'Johnson',
      registrationNumber: 'FR003',
      gender: 'Male',
      dateOfBirth: DateTime(1988, 2, 10),
      village: 'River Bend',
      farms: [
        Farm(
          id: 'F3',
          enumeratorName: 'Emily Ray',
          kebeleName: 'Kebele C',
          woredaName: 'Woreda 3',
          cooperativeName: 'Coop Gamma',
          farmerName: 'David Johnson',
          collectingCenterName: 'Center Delta',
          plotNumber: 'P3',
          latitude: -1.2800,
          longitude: 36.8500,
          gpsAccuracy: 11.0,
          plotSize: 1.8,
          coffeeAge: 4,
          coffeeType: 'Semi-Forest',
          disturbance: 2,
          geolocationFlagged: true,
          isApproved: false,
          images: ['https://images.unsplash.com/photo-1623578540859-adf2416e09b3'],
          additionalInfo: null,
        ),
      ],
    ),
    Farmer(
      id: '4',
      firstName: 'Sarah',
      lastName: 'Wilson',
      registrationNumber: 'FR004',
      gender: 'Female',
      dateOfBirth: DateTime(1992, 11, 3),
      village: 'Oak Grove',
      farms: [
        Farm(
          id: 'F4',
          enumeratorName: 'Liam King',
          kebeleName: 'Kebele D',
          woredaName: 'Woreda 4',
          cooperativeName: 'Coop Delta',
          farmerName: 'Sarah Wilson',
          collectingCenterName: 'Center Gamma',
          plotNumber: 'P4',
          latitude: -1.2800,
          longitude: 36.8500,
          gpsAccuracy: 4.0,
          plotSize: 2.2,
          coffeeAge: 3,
          coffeeType: 'Wild Coffee',
          disturbance: 1,
          geolocationFlagged: false,
          isApproved: true,
          images: ['https://images.unsplash.com/photo-1567374578224-b57c510ddbf3'],
          additionalInfo: 'Part of a co-op.',
        ),
      ],
    ),
    Farmer(
      id: '5',
      firstName: 'Michael',
      lastName: 'Brown',
      registrationNumber: 'FR005',
      gender: 'Male',
      dateOfBirth: DateTime(1970, 7, 18),
      village: 'Pine Ridge',
      farms: [
        Farm(
          id: 'F5',
          enumeratorName: 'Chloe Smith',
          kebeleName: 'Kebele E',
          woredaName: 'Woreda 5',
          cooperativeName: 'Coop Epsilon',
          farmerName: 'Michael Brown',
          collectingCenterName: 'Center Zeta',
          plotNumber: 'P5',
          latitude: -5.2800,
          longitude: 9.8500,
          gpsAccuracy: 6.8,
          plotSize: 2.9,
          coffeeAge: 6,
          coffeeType: 'Plantation',
          disturbance: 0,
          geolocationFlagged: false,
          isApproved: true,
          images: ['https://images.unsplash.com/reserve/HgZuGu3gSD6db21T3lxm_San%20Zenone.jpg'],
          additionalInfo: 'Dairy feed production.',
        ),
      ],
    ),
  ];
}
