// Sample Data Generator
import 'package:coffee_app/models/data_models.dart' show Farm, Farmer;

List<Farmer> generateSampleFarmers() {
  return [
    Farmer(
      id: '1',
      firstName: 'John',
      lastName: 'Smith',
      registrationNumber: 'FR001',
      gender: 'Male',
      dateOfBirth: DateTime(1980, 5, 15),
      village: 'Green Valley',
      farms: [
        Farm(
          id: 'F1',
          name: 'Smith Farm',
          size: 50.0,
          cropType: 'Corn',
          images: [
            'https://images.unsplash.com/photo-1592856908193-b9934576cf3d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmllbGR8ZW58MHx8MHx8fDA%3D',
            'https://images.unsplash.com/photo-1587990754909-18ae9d92c8e8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZmllbGR8ZW58MHx8MHx8fDA%3D',
            'https://images.unsplash.com/photo-1587990754909-18ae9d92c8e8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZmllbGR8ZW58MHx8MHx8fDA%3D',
          ],
          location: 'Green Valley North',
          isApproved: true,
          additionalInfo: 'High yield expected this season.',
        ),
        Farm(
          id: 'F2',
          name: 'North Field',
          size: 30.0,
          cropType: 'Wheat',
          images: [
            'https://images.unsplash.com/photo-1587990754909-18ae9d92c8e8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8ZmllbGR8ZW58MHx8MHx8fDA%3D',
          ],
          location: 'Green Valley North',
          isApproved: false,
          additionalInfo: null,
        ),
      ],
    ),
    Farmer(
      id: '2',
      firstName: 'Maria',
      lastName: 'Garcia',
      registrationNumber: 'FR002',
      gender: 'Female',
      dateOfBirth: DateTime(1975, 8, 22),
      village: 'Sunny Hills',
      farms: [
        Farm(
          id: 'F3',
          name: 'Garcia Ranch',
          size: 75.0,
          cropType: 'Vegetables',
          images: ['https://images.unsplash.com/photo-1560493676-04071c5f467b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGZpZWxkfGVufDB8fDB8fHww'],
          location: 'Sunny Hills East',
          isApproved: true,
          additionalInfo: 'Certified organic.',
        ),
      ],
    ),
    Farmer(
      id: '3',
      firstName: 'David',
      lastName: 'Johnson',
      registrationNumber: 'FR003',
      gender: 'Male',
      dateOfBirth: DateTime(1988, 2, 10),
      village: 'River Bend',
      farms: [
        Farm(
          id: 'F4',
          name: 'Johnson Fields',
          size: 40.0,
          cropType: 'Soybeans',
          images: ['https://images.unsplash.com/35/Ov8Hg5LlQriTimkB3PEl_kreativgrund_Weizenfeld.jpg?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGZpZWxkfGVufDB8fDB8fHww'],
          location: 'River Bend West',
          isApproved: false,
          additionalInfo: null,
        ),
        Farm(
          id: 'F5',
          name: 'East Plot',
          size: 25.0,
          cropType: 'Barley',
          images: ['assets/images/farm5.jpg'],
          location: 'River Bend East',
          isApproved: true,
          additionalInfo: 'Recently expanded.',
        ),
        Farm(
          id: 'F6',
          name: 'West Meadow',
          size: 35.0,
          cropType: 'Oats',
          images: ['https://images.unsplash.com/photo-1623578540859-adf2416e09b3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGZpZWxkfGVufDB8fDB8fHww'],
          location: 'River Bend West',
          isApproved: true,
          additionalInfo: null,
        ),
      ],
    ),
    Farmer(
      id: '4',
      firstName: 'Sarah',
      lastName: 'Wilson',
      registrationNumber: 'FR004',
      gender: 'Female',
      dateOfBirth: DateTime(1992, 11, 3),
      village: 'Oak Grove',
      farms: [
        Farm(
          id: 'F7',
          name: 'Wilson Organic',
          size: 60.0,
          cropType: 'Organic Vegetables',
          images: ['https://images.unsplash.com/photo-1567374578224-b57c510ddbf3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGZpZWxkfGVufDB8fDB8fHww'],
          location: 'Oak Grove Central',
          isApproved: true,
          additionalInfo: 'Part of a co-op.',
        ),
      ],
    ),
    Farmer(
      id: '5',
      firstName: 'Michael',
      lastName: 'Brown',
      registrationNumber: 'FR005',
      gender: 'Male',
      dateOfBirth: DateTime(1970, 7, 18),
      village: 'Pine Ridge',
      farms: [
        Farm(
          id: 'F8',
          name: 'Brown Dairy Farm',
          size: 120.0,
          cropType: 'Grass/Hay',
          images: ['https://images.unsplash.com/reserve/HgZuGu3gSD6db21T3lxm_San%20Zenone.jpg?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGZpZWxkfGVufDB8fDB8fHww'],
          location: 'Pine Ridge South',
          isApproved: true,
          additionalInfo: 'Dairy feed production.',
        ),
        Farm(
          id: 'F9',
          name: 'South Pasture',
          size: 80.0,
          cropType: 'Alfalfa',
          images: ['assets/images/farm9.jpg'],
          location: 'Pine Ridge South',
          isApproved: false,
          additionalInfo: null,
        ),
      ],
    ),
  ];
}
